### ISSUE TITLE
Working radios

### ISSUE THREAD

**Issue by Canadian-bacon1867** [Rubberbandits/mafiarp-issues#38]
Working radios for PD and EMS (conjoined between two factions)

- Item that when enabled allows all PD and ems to use the radio. (except when restrained)
- Only usable / useful by PD or EMS to prevent meta from criminals
- radios can be used in chat with U (team chat) or over mic. (hold G or any other hotkey)
- Eliminates the need for discord radio channels and brings us closer to reducing discord metagaming.

We can also add a regular radio item for criminals to buy and use at the BLACK MARKET

- Works the same except it would be set to a freq and channel
- Allows factions to change their freq whenevr theirs is compromised
- Ban discord call metagame entirely and force players to use in game comms

**Comment by Canadian-bacon1867** [comment]
**Potential Addition:** Volume button. Allows users to adjust the volume of their radios.

**Comment by Canadian-bacon1867** [comment]
Nearly done!

Add separate Police Radio for NYPD and ERS ONLY

**Comment by Canadian-bacon1867** [comment]
Above and https://github.com/Rubberbandits/mafiarp-issues/issues/68

**Comment by Pendred** [comment]
Done
