### ISSUE TITLE
More medals for NYPD to cum over. Maybe medals for EMS?

### ISSUE THREAD

**Issue by Canadian-bacon1867** [Rubberbandits/mafiarp-issues#46]
Just a thought, i know some cops were asking for new ish medals / badges a bit ago. 

https://cdn.discordapp.com/attachments/787791901645996062/861465628899803176/image1.jpg

https://cdn.discordapp.com/attachments/787791901645996062/861465628706471987/image0.webp

Maybe medals for EMS signifying levels of medical training or competence, just a thought.

**Comment by Pendred** [comment]
get them to provide medals

**Comment by Canadian-bacon1867** [comment]
https://docs.google.com/spreadsheets/d/1EjNWr_M5iWNXEPlmsphp0s12qe-RSpnA08_Mu3tDxz0/edit?usp=sharing

**Comment by Canadian-bacon1867** [comment]
![image](https://user-images.githubusercontent.com/33945552/134795126-3ff5f1a6-a6f1-46c9-96e7-ada8e6330e68.png)

**Comment by Canadian-bacon1867** [comment]
add one called:
   emsbadge

choose between these two images

https://cdn.discordapp.com/attachments/711009856332496988/892142967794569246/ems1.png

https://cdn.discordapp.com/attachments/711009856332496988/892142977013645402/ems2.png

I personally prefer the first.

**Comment by Canadian-bacon1867** [comment]
Steeles Investigative Excellence
 
 https://media.discordapp.net/attachments/795183007685148742/906728232517238804/Gamer.png?width=493&height=676
 
 
![image](https://user-images.githubusercontent.com/33945552/144195349-e6064124-7aae-4d71-8ce2-135110c49f9e.png)
