### ISSUE TITLE
Invisible guns

### ISSUE THREAD

**Issue by Canadian-bacon1867** [Rubberbandits/mafiarp-issues#49]
![image](https://user-images.githubusercontent.com/33945552/133940376-4765fdd9-2e12-479c-a9b1-688c6e5396c3.png)

People often report guns being invisible in people's hands, whether its a rifle or pistol. It's not consistent either, some players their guns are invisible and others are visible.

**Comment by Pendred** [comment]
I believe Ultra is working on getting us over to a new weapon base, so we'll have to wait for that.
