### ISSUE TITLE
IDs

### ISSUE THREAD

**Issue by Canadian-bacon1867** [Rubberbandits/mafiarp-issues#55]
Not pressing but this is what IDs look like

![image](https://user-images.githubusercontent.com/33945552/134832189-62383c17-b67c-4499-91d4-509fc43f2ac2.png)

Reposition the head. The shoulders don't have to be shown. Clothing is unimportant,

**Comment by Pendred** [comment]
looks fine to me.

https://imgur.com/lVg1V1k
