### ISSUE TITLE
Pay change

### ISSUE THREAD

**Issue by Canadian-bacon1867** [Rubberbandits/mafiarp-issues#62]
every whatever tick players receive a paycheck. The base paycheck is 25$

Increase paycheck for legal factions such as:

NYPD - $200
ERS - $100
State gov - $150
Local Gov - $100

**Comment by Pendred** [comment]
Gov paycheques are more frequent than others, they get paid every 20 minutes, 3 times an hour. They make roughly what you've asked for in an hour.
