### ISSUE TITLE
Changes to PD armoury.

### ISSUE THREAD

**Issue by Canadian-bacon1867** [Rubberbandits/mafiarp-issues#67]
Make meds or certain good weapons cost money to take out. Similar to the 1942rp on prom where soldiers pay for their meds

Bandages ($10), stitches ($20) for example

Maybe colt commando is 200$ or a shotgun is $50, Pistols can be free. Just to reduce use of constant heavy weapons or reduce free med item abuse.
Do same with FBI locker ^

Restraints will be replaced with cuffs soon

Also since you have to be in the NYPD faction to use the locker the cop flag isnt used to its full potential right now.

A thing PD likes doing is to not let Cadets have guns until they are fully trained. But other than yelling at them or removing them they cant do much.

Make it so if an NYPD member accesses the armoury but DOES NOT have the police flag they can only take out tazer, baton, radio and meds.

This means staff dont give the cop flag right away and it helps prevents cadets from insta getting access to guns and mass rdming.

thank you.

**Comment by Canadian-bacon1867** [comment]
Made a list for price stuff:

L Flag = Regular Police Locker

Spike Strip ($25)
M1A1 Carbine ($100)
Bandages ($5)
Stitches ($10)

J Flag = Special Police Locker

Spike Strip ($25)
Mossberg M590 ($50)
M1A1 Carbine ($100)
MP5 ($100)
Tear Gas ($25)
Smoke nades ($10)
Remmington M40A1 ($150)
Colt Commando ($200)
Bandages ($5)
Stitches ($10)

**Comment by Pendred** [comment]
done, don't think weapons need prices as they can only be taken by PD.

**Comment by Canadian-bacon1867** [comment]
Weapon prices on PD aren't to deter abuse with them just to slow down use since people always complain about cops patrolling with big fuck off rifles
So if they foot officer is constantly walking around with a colt commando at least if he dies he has to pay a price for carrying the OP gun around 
the normal carry weapons like sidearms all remain free

**Comment by Canadian-bacon1867** [comment]
Partially done. No prices on large weapons causes officers to run around with them without repercussion constantly.

![image](https://user-images.githubusercontent.com/33945552/139016193-2cf2578b-2e5b-487e-a776-adb8b1987ccd.png)
