### ISSUE TITLE
Punching

### ISSUE THREAD

**Issue by Canadian-bacon1867** [Rubberbandits/mafiarp-issues#69]
Punching is the main weapon of the minges, we should do one of two things,

1. Seriously reduce the chance of a punch breaking your leg. Someone can run up, crouch, punch your leg once or twice and break it. IF we make the chance for a punch to break a leg nearly zero we can promote the use of melee weapons for such actions.

2. Reduce the overall damage a punch does. I just think It's generally too high, cutting it in half may be a lot but for someone who maxed strength they can't just run around knocking people.

**Comment by Pendred** [comment]
Reduced default damage for hands from 5 to 2, if you hit someone with hands you can't break their legs. 
If you really want it to just be reduced instead of being removed, I can do that.

**Comment by Pendred** [comment]
Connecting a punch with 30/30 strength will deal 16 damage instead of 21, connecting a punch with 0 strength deals 3 damage.
