### ISSUE TITLE
Guns persist on users backs despite being put into banks.

### ISSUE THREAD

**Issue by Canadian-bacon1867** [Rubberbandits/mafiarp-issues#70]
https://cdn.discordapp.com/attachments/900131374512619550/900829725067468810/2021-10-21_21-34-06.mkv

**Comment by Canadian-bacon1867** [comment]
doesnt always occur, specific instance is unknown

**Comment by Canadian-bacon1867** [comment]
Weapons persisted when i picked them up and they went into an unequipped backpack, disconnected, reconnected i then sold the weapons from the backpack to an NPC
![image](https://user-images.githubusercontent.com/33945552/138588100-c9031f7a-ef9f-407a-b79a-5ad2ee6c0efe.png)

**Comment by Canadian-bacon1867** [comment]
Death does not solve the issue. Cannot get rid of these

Nor can i recreate the method used in the user made video

**Comment by Canadian-bacon1867** [comment]
Does not fix after restart

**Comment by Canadian-bacon1867** [comment]
User also seems to be able to sell the gun !

![image](https://user-images.githubusercontent.com/33945552/139540863-4e416b6d-d6eb-46c2-af1b-2ad3e3b9fad1.png)


![image](https://user-images.githubusercontent.com/33945552/139540857-560d37cb-3166-4de7-be89-ea698ceaca77.png)

![image](https://user-images.githubusercontent.com/33945552/139540860-845ff09c-6e10-4f74-bde5-3c50c770eded.png)

**Comment by Canadian-bacon1867** [comment]
Another instance found when a use was given a weapon with a full inventory

![image](https://user-images.githubusercontent.com/33945552/145454740-513dc768-b4ae-471e-a9f7-e5defdfd9779.png)
![image](https://user-images.githubusercontent.com/33945552/145454751-a8187259-9aff-409b-a167-757350265647.png)

**Comment by Pendred** [comment]
fucking backpacks
