### ISSUE TITLE
Ghost cars

### ISSUE THREAD

**Issue by Canadian-bacon1867** [Rubberbandits/mafiarp-issues#86]
You can ghost drive cars by hopping onto a chess game while driving

https://cdn.discordapp.com/attachments/828258959978790932/904831638058463262/Garrys_Mod_x64_2021-11-01_20-35-21.mp4

**Comment by Pendred** [comment]
Doesn't really have much consequence, they're still registered as the driver, and shooting it will kill them. Difficult to fix, would be a waste of time.
