### ISSUE TITLE
Arrest NPC meta

### ISSUE THREAD

**Issue by Canadian-bacon1867** [Rubberbandits/mafiarp-issues#87]
![image](https://user-images.githubusercontent.com/33945552/139968848-c6ea1767-87fa-414e-b97f-286ce6d4847b.png)

**Comment by Pendred** [comment]
I'll make it char ID instead

**Comment by Pendred** [comment]
although by the time PD put you in jail they're bound to know your name lol

**Comment by Canadian-bacon1867** [comment]
![image](https://user-images.githubusercontent.com/33945552/145889142-c80e1377-1ea2-4457-8111-9c7d996a33e0.png)
Name is fine. It's faction that can be metagamed
